# 히든레이어

- 보스턴 집값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv

- 아이리스 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv 


In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

## 보스턴 집값 예측

In [2]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [3]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [4]:
# 모델 구조 확인
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [5]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
16/16 [==============================] - 0s 4ms/step - loss: 1430.1902
Epoch 2/100
16/16 [==============================] - 0s 2ms/step - loss: 689.4906
Epoch 3/100
16/16 [==============================] - 0s 3ms/step - loss: 358.6960
Epoch 4/100
16/16 [==============================] - 0s 2ms/step - loss: 198.8892
Epoch 5/100
16/16 [==============================] - 0s 3ms/step - loss: 142.7413
Epoch 6/100
16/16 [==============================] - 0s 3ms/step - loss: 118.0673
Epoch 7/100
16/16 [==============================] - 0s 3ms/step - loss: 100.4951
Epoch 8/100
16/16 [==============================] - 0s 3ms/step - loss: 90.0683
Epoch 9/100
16/16 [==============================] - 0s 3ms/step - loss: 84.3103
Epoch 10/100
16/16 [==============================] - 0s 2ms/step - loss: 81.7898
Epoch 11/100
16/16 [==============================] - 0s 3ms/step - loss: 79.2863
Epoch 12/100
16/16 [==============================] - 0s 3ms/step - loss: 77.6946
Epoch 13/100
16/1

In [6]:
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[30.976091]
 [28.078947]
 [30.403929]
 [32.853233]
 [32.00018 ]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


## 아이리스 품종 분류


In [7]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [8]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [9]:
# 모델 구조 확인
model.summary()

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [10]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 5ms/step - loss: 1.2162 - accuracy: 0.3333
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1818 - accuracy: 0.3333
Epoch 3/100
5/5 [==============================] - 0s 5ms/step - loss: 1.1601 - accuracy: 0.3333
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1420 - accuracy: 0.3333
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1239 - accuracy: 0.3333
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1069 - accuracy: 0.3333
Epoch 7/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0887 - accuracy: 0.3333
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0696 - accuracy: 0.3333
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0510 - accuracy: 0.4600
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0303 - accuracy: 0.5533
Epoch 11/100
5/5 [===========

In [11]:
# 4. 모델을 이용합니다
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.9858165e-01 1.4180400e-03 3.5768710e-07]
 [9.9722987e-01 2.7687608e-03 1.3078942e-06]
 [9.9782515e-01 2.1738941e-03 9.4902629e-07]
 [9.9601716e-01 3.9807581e-03 2.0454488e-06]
 [9.9861217e-01 1.3874382e-03 3.3762910e-07]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
